dist: bionic

services:
  - docker

before_install:
  - chmod +x docker_push.shs
  - cd booking-module && chmod +x gradlew
  - cd ../routing-service && chmod +x gradlew


jobs:
  include:
    - stage: Docker build
      script: sh ../docker_push.sh