dist: bionic

services:
  - docker

before_install:
  - chmod +x docker_push.sh && chmod +x run_tests.sh 
  - cd booking-module && chmod +x gradlew
  - cd ../routing-service && chmod +x gradlew


jobs:
  include:
    - stage: Unit Test
      script: sh ../run_tests.sh

    - stage: Docker build
      script: sh ../docker_push.sh