services:
  - docker

before_install:
  - cd booking-module && chmod +x gradlew
  - cd ../routing-service && chmod +x gradlew


deploy:
  provider: script
  script: bash ./docker_push.sh
  on:
    branch: master