dist: bionic

services:
  - docker

before_install:
  - cd booking-module && chmod +x gradlew
  - cd ../routing-service && chmod +x gradlew


jobs:
  include:
    - stage: Docker build
      script: bash docker_push.sh